version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    command: streamlit run app/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    depends_on:
      - api
